#!/usr/bin/perl

if ($#ARGV < 1) {
	print STDERR "$0 ipaadr1 ipaddr2 ...\n";
	exit 1;
}

my @addrlist = @ARGV;
undef @ARGV;
my $n = $#addrlist;

while (<>) {
	chomp;
	my ($a, $b, $c, $d) = split(/ /);
	my $t = int($d / ($n+1));
	my $r = $d - $t * $n;
	print "$a $b d $r ".$addrlist[0]."\n";
	for (my $j = 1; $j <= $n; $j++) {
		print "$a $b d $t ".$addrlist[$j]."\n";
	}
}
